#!/usr/bin/perl -w
# -*- cperl -*-
# vim: ft=perl

=head1 NAME

snmp__pfstates - Munin plugin to retrieve istate table size from a PfSense SNMP
device.

=head1 CONFIGURATION

As a rule SNMP plugins need site specific configuration.  The default
configuration (shown here) will only work on insecure sites/devices.

   [snmp_*]
        env.version 2
        env.community public

In general SNMP is not very secure at all unless you use SNMP version
3 which supports authentication and privacy (encryption).  But in any
case the community string for your devices should not be "public".

Please see 'perldoc Munin::Plugin::SNMP' for further configuration
information.

=head1 INTERPRETATION


=head1 MIB INFORMATION

This plugin requires support for the DISMAN-EVENT-MIB authored by the
IETF Distributed Management Working Group.  It reports the
contents of the sysUpTimeInstance OID.

=head1 MAGIC MARKERS

  #%# family=snmpauto
  #%# capabilities=snmpconf

=head1 VERSION

  $Id$

=head1 BUGS

None known.

=head1 AUTHOR

Copyright (C) 2000-2017 by various authors.

Original Nagios plugin: Sébastien Barbereau.

=head1 LICENSE

GPLv2 or (at your option) any later version.

=cut

use strict;
use Munin::Plugin::SNMP;

if (defined $ARGV[0] and $ARGV[0] eq "snmpconf") {
        print "require 1.3.6.1.4.1.12325.1.200.1.3.1.0 [0-9]\n"; # Number
        exit 0;
}

if (defined $ARGV[0] and $ARGV[0] eq "config") {
    my ($host) = Munin::Plugin::SNMP->config_session();
        print "host_name $host\n" unless $host eq 'localhost';
        print "graph_title System State table size
graph_args --base 1000 -l 0
graph_vlabel states
graph_category system
graph_info This graph shows the number of states of the network stack.
pfstates.label pfstates
pfstates.info The number of network states.
pfstates.draw AREA
";
        exit 0;
}

my $session = Munin::Plugin::SNMP->session(-translate =>
                                           [ -timeticks => 0x0 ]);

my $state_table_size = $session->get_single (".1.3.6.1.4.1.12325.1.200.1.3.1.0") || 'U';

print "Retrived state table size is '$state_table_size'\n" if $Munin::Plugin::SNMP::DEBUG;

print "pfstates.value ", $state_table_size, "\n";
